# Generated by Django 4.0.6 on 2022-11-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apnipustak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='isbn_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
